FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache bash openssl libc6-compat

COPY package*.json ./
RUN npm ci

# copy everything EXCEPT node_modules via .dockerignore
COPY . .
COPY prisma.config.ts ./

COPY src ./src
# Prisma generate
RUN npx prisma generate


RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown -R appuser:appgroup /app
USER appuser

EXPOSE 5003

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]