FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache bash openssl libc6-compat

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma generate

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown -R appuser:appgroup /app
USER appuser

ENV NODE_OPTIONS="--max-old-space-size=512"

CMD ["node", "--max-old-space-size=512", "src/infra/queues/workers/emailWorker.js"]