FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache bash openssl libc6-compat

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

RUN chown appuser:appgroup /app

USER appuser

COPY --chown=appuser:appgroup package*.json ./
RUN npm ci

COPY --chown=appuser:appgroup . .

RUN npx prisma generate

CMD ["node", "src/infra/queues/workers/emailWorker.js"]